# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: '1.14' # The Go version to download (if necessary) and use.

    # Runs a single command using the runners shell
    - name: Install Dependencies
      run: |
        sudo apt update -y -qq
        sudo apt install libgmp-dev g++ wget cmake libboost-all-dev nodejs python3-pip python3-dev valgrind -y -qq

    # Runs a set of commands using the runners shell
    - name: Test
      run: |
        go get
        make test
